name: Build and Deploy .NET Application

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./transactiva/transactiva.csproj

      - name: Build
        run: dotnet build ./transactiva/transactiva.csproj --configuration Release

      - name: Publish
        run: dotnet publish ./transactiva/transactiva.csproj --configuration Release --output ./published

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          source: "./published/"
          target: "/home/ubuntu/appdotnet/published"

